// This runner is auto-generated by Brittle

import { default as test } from 'brittle';

async function runTests() {
  test.pause();

  await import('./check/check.test.js');
  await import('./fileUtils.test.js');
  await import('./functions.test.js');

  //TODO add test MsgUtils
  //TODO add test Apply function

  //TODO add test MsgUtils
  //TODO add test Functions
  //TODO add test FileUtils
  //TODO add test Apply function

  test.resume();
}

runTests();
