// This runner is auto-generated by Brittle

import { default as test } from 'brittle';

async function runTests() {
  test.pause();

  await import('./check.test.js');

  test.resume();
}

runTests();
