syntax = "proto3";

package consensus.v1;

// Challenge data use the fixed V1 domain separator followed by fields 1 to 6.
// Proof data are in field 7.
message ProofProposal {
  bytes network_id = 1;
  bytes epoch = 2; // epoch number (for what epoch the proof is for current_epoch + 1)
  bytes previous_epoch_record_hash = 3; // BLAKE3 hash of the encoded previous epoch record
  bytes proposer = 4; // TRAC address of the proposer
  bytes difficulty = 5; // uint32_be difficulty
  bytes discriminant_bit_size = 6; // uint16_be discriminant_bit_size
  bytes proof = 7; // bytes blob  that is actually y || pi
  bytes signature = 8; // SIG(challenge_data + proof)
}
