// This runner is auto-generated by Brittle

import { default as test } from 'brittle';

async function runTests() {
    test.pause();
    await import('./ValidatorHealthCheckService.test.js');
    await import('./TransactionRateLimiterService.test.js');
    await import('./ConnectionManager.test.js');
    await import('./PendingRequestService.test.js');
    await import('./TransactionCommitService.test.js');
    test.resume();
}

await runTests();
