import applyOperationsGenerated from '../codecs/apply/applyOperations.generated.cjs';
import networkV1Generated from '../codecs/network/v1/networkV1.generated.cjs';
import consensusV1Generated from '../codecs/consensus/v1/consensusV1.generated.cjs';
import b4a from 'b4a'
// TODO: We are going to have a lot of contstants. It would be good, to separate them into different files.

const { OperationType: ApplyOperationType } = applyOperationsGenerated.apply.operations;
const { MessageType: NetworkMessageType } = networkV1Generated.network.v1;
const { MessageType: ConsensusMessageType } = consensusV1Generated.consensus.v1;
const { ResultCode: SharedResultCode } = networkV1Generated.common.v1;
//ATTENTION - THIS IS USED IN THE APPLY FUNCTION!
export const EntryType = Object.freeze({
    ADMIN: 'admin',
    INDEXERS: 'indexers',
    WRITERS_LENGTH: 'wrl',
    WRITERS_INDEX: 'wri/',
    WRITER_ADDRESS: 'wka/',
    DEPLOYMENT: 'deployment/',
    INITIALIZATION: 'init',
    LICENSE_COUNT: 'lc',
    LICENSE_INDEX: 'li/',
    EPOCH_CURRENT: '/epoch/current',
    EPOCH: `/epoch/`,              // Epoch hashes are stored under `/epoch/<n>`
    EPOCH_HASH: `/epochHash/`,     // Epoch proof payloads are stored under `/epochHash/<epochHashHex>`
    VDF_PARAMS: '/parameters/vdf', // TODO: DELETE
    CONSENSUS_CONFIG_CURRENT: '/consensus/config/current',
    CONSENSUS_CONFIG_RECORD: '/consensus/config/record/',

});

//ATTENTION - THIS IS USED IN THE APPLY FUNCTION!
export const OperationType = Object.freeze({
    ADD_ADMIN: ApplyOperationType.ADD_ADMIN,
    DISABLE_INITIALIZATION: ApplyOperationType.DISABLE_INITIALIZATION,
    BALANCE_INITIALIZATION: ApplyOperationType.BALANCE_INITIALIZATION,
    APPEND_WHITELIST: ApplyOperationType.APPEND_WHITELIST,
    ADD_WRITER: ApplyOperationType.ADD_WRITER,
    REMOVE_WRITER: ApplyOperationType.REMOVE_WRITER,
    ADMIN_RECOVERY: ApplyOperationType.ADMIN_RECOVERY,
    ADD_INDEXER: ApplyOperationType.ADD_INDEXER,
    REMOVE_INDEXER: ApplyOperationType.REMOVE_INDEXER,
    BAN_VALIDATOR: ApplyOperationType.BAN_VALIDATOR,
    BOOTSTRAP_DEPLOYMENT: ApplyOperationType.BOOTSTRAP_DEPLOYMENT,
    TX: ApplyOperationType.TX,
    TRANSFER: ApplyOperationType.TRANSFER,
    SET_EPOCH: ApplyOperationType.SET_EPOCH,
    SET_GENESIS_EPOCH: ApplyOperationType.SET_GENESIS_EPOCH,
    SET_CONSENSUS_CONFIG: ApplyOperationType.SET_CONSENSUS_CONFIG,
});

export const NetworkOperationType = Object.freeze({
    LIVENESS_REQUEST: NetworkMessageType.MESSAGE_TYPE_LIVENESS_REQUEST,
    LIVENESS_RESPONSE: NetworkMessageType.MESSAGE_TYPE_LIVENESS_RESPONSE,
    BROADCAST_TRANSACTION_REQUEST: NetworkMessageType.MESSAGE_TYPE_BROADCAST_TRANSACTION_REQUEST,
    BROADCAST_TRANSACTION_RESPONSE: NetworkMessageType.MESSAGE_TYPE_BROADCAST_TRANSACTION_RESPONSE,
});

export const ConsensusOperationType = Object.freeze({
    UNSPECIFIED: ConsensusMessageType.MESSAGE_TYPE_UNSPECIFIED,
    PROOF_PROPOSAL: ConsensusMessageType.MESSAGE_TYPE_PROOF_PROPOSAL,
    PROOF_PROPOSAL_APPROVAL: ConsensusMessageType.MESSAGE_TYPE_PROOF_PROPOSAL_APPROVAL
});

export const ConsensusProtocolVersion = Object.freeze({
    V1: 1,
});

export const ConsensusResultCode = Object.freeze({
    UNSPECIFIED: SharedResultCode.RESULT_CODE_UNSPECIFIED,
    OK: SharedResultCode.RESULT_CODE_OK,
    INVALID_PAYLOAD: SharedResultCode.RESULT_CODE_INVALID_PAYLOAD,
    UNEXPECTED_ERROR: SharedResultCode.RESULT_CODE_UNEXPECTED_ERROR,
    SCHEMA_VALIDATION_FAILED: SharedResultCode.RESULT_CODE_CONSENSUS_SCHEMA_VALIDATION_FAILED,
    BAD_PROTOCOL_VERSION: SharedResultCode.RESULT_CODE_CONSENSUS_BAD_PROTOCOL_VERSION,
    WRONG_NETWORK_ID: SharedResultCode.RESULT_CODE_CONSENSUS_WRONG_NETWORK_ID,
    CONSENSUS_CONFIG_MISMATCH: SharedResultCode.RESULT_CODE_CONSENSUS_CONFIG_MISMATCH,
    VDF_PROOF_INVALID: SharedResultCode.RESULT_CODE_CONSENSUS_VDF_PROOF_INVALID,
    ADDRESS_INVALID: SharedResultCode.RESULT_CODE_CONSENSUS_ADDRESS_INVALID,
    PUBLIC_KEY_MISMATCH: SharedResultCode.RESULT_CODE_CONSENSUS_PUBLIC_KEY_MISMATCH,
    PROPOSAL_SIGNATURE_INVALID: SharedResultCode.RESULT_CODE_CONSENSUS_PROPOSAL_SIGNATURE_INVALID,
    RESPONSE_SIGNATURE_INVALID: SharedResultCode.RESULT_CODE_CONSENSUS_RESPONSE_SIGNATURE_INVALID,
    APPROVAL_SIGNATURE_INVALID: SharedResultCode.RESULT_CODE_CONSENSUS_APPROVAL_SIGNATURE_INVALID,
    OPERATION_TYPE_INVALID: SharedResultCode.RESULT_CODE_CONSENSUS_OPERATION_TYPE_INVALID,
    RESPONSE_APPROVAL_INVALID: SharedResultCode.RESULT_CODE_CONSENSUS_RESPONSE_APPROVAL_INVALID,
    EPOCH_INVALID: SharedResultCode.RESULT_CODE_CONSENSUS_EPOCH_INVALID,
    PREVIOUS_EPOCH_RECORD_HASH_INVALID: SharedResultCode.RESULT_CODE_CONSENSUS_PREVIOUS_EPOCH_RECORD_HASH_INVALID,
    INDEXER_ROLE_INVALID: SharedResultCode.RESULT_CODE_CONSENSUS_INDEXER_ROLE_INVALID,
});

export const NetworkResultCode = Object.freeze({
    UNSPECIFIED: SharedResultCode.RESULT_CODE_UNSPECIFIED,
    OK: SharedResultCode.RESULT_CODE_OK,
    INVALID_PAYLOAD: SharedResultCode.RESULT_CODE_INVALID_PAYLOAD,
    RATE_LIMITED: SharedResultCode.RESULT_CODE_RATE_LIMITED,
    SIGNATURE_INVALID: SharedResultCode.RESULT_CODE_SIGNATURE_INVALID,
    UNEXPECTED_ERROR: SharedResultCode.RESULT_CODE_UNEXPECTED_ERROR,
    TIMEOUT: SharedResultCode.RESULT_CODE_TIMEOUT,
    NODE_HAS_NO_WRITE_ACCESS: SharedResultCode.RESULT_CODE_NODE_HAS_NO_WRITE_ACCESS,
    TX_ACCEPTED_PROOF_UNAVAILABLE: SharedResultCode.RESULT_CODE_TX_ACCEPTED_PROOF_UNAVAILABLE,
    NODE_OVERLOADED: SharedResultCode.RESULT_CODE_NODE_OVERLOADED,
    TX_ALREADY_PENDING: SharedResultCode.RESULT_CODE_TX_ALREADY_PENDING,
    OPERATION_TYPE_UNKNOWN: SharedResultCode.RESULT_CODE_OPERATION_TYPE_UNKNOWN,
    SCHEMA_VALIDATION_FAILED: SharedResultCode.RESULT_CODE_SCHEMA_VALIDATION_FAILED,
    REQUESTER_ADDRESS_INVALID: SharedResultCode.RESULT_CODE_REQUESTER_ADDRESS_INVALID,
    REQUESTER_PUBLIC_KEY_INVALID: SharedResultCode.RESULT_CODE_REQUESTER_PUBLIC_KEY_INVALID,
    TX_HASH_MISMATCH: SharedResultCode.RESULT_CODE_TX_HASH_MISMATCH,
    TX_SIGNATURE_INVALID: SharedResultCode.RESULT_CODE_TX_SIGNATURE_INVALID,
    TX_EXPIRED: SharedResultCode.RESULT_CODE_TX_EXPIRED,
    TX_ALREADY_EXISTS: SharedResultCode.RESULT_CODE_TX_ALREADY_EXISTS,
    OPERATION_ALREADY_COMPLETED: SharedResultCode.RESULT_CODE_OPERATION_ALREADY_COMPLETED,
    REQUESTER_NOT_FOUND: SharedResultCode.RESULT_CODE_REQUESTER_NOT_FOUND,
    INSUFFICIENT_FEE_BALANCE: SharedResultCode.RESULT_CODE_INSUFFICIENT_FEE_BALANCE,
    EXTERNAL_BOOTSTRAP_EQUALS_MSB_BOOTSTRAP: SharedResultCode.RESULT_CODE_EXTERNAL_BOOTSTRAP_EQUALS_MSB_BOOTSTRAP,
    SELF_VALIDATION_FORBIDDEN: SharedResultCode.RESULT_CODE_SELF_VALIDATION_FORBIDDEN,
    ROLE_NODE_ENTRY_NOT_FOUND: SharedResultCode.RESULT_CODE_ROLE_NODE_ENTRY_NOT_FOUND,
    ROLE_NODE_ALREADY_WRITER: SharedResultCode.RESULT_CODE_ROLE_NODE_ALREADY_WRITER,
    ROLE_NODE_NOT_WHITELISTED: SharedResultCode.RESULT_CODE_ROLE_NODE_NOT_WHITELISTED,
    ROLE_NODE_NOT_WRITER: SharedResultCode.RESULT_CODE_ROLE_NODE_NOT_WRITER,
    ROLE_NODE_IS_INDEXER: SharedResultCode.RESULT_CODE_ROLE_NODE_IS_INDEXER,
    ROLE_ADMIN_ENTRY_MISSING: SharedResultCode.RESULT_CODE_ROLE_ADMIN_ENTRY_MISSING,
    ROLE_INVALID_RECOVERY_CASE: SharedResultCode.RESULT_CODE_ROLE_INVALID_RECOVERY_CASE,
    ROLE_UNKNOWN_OPERATION: SharedResultCode.RESULT_CODE_ROLE_UNKNOWN_OPERATION,
    ROLE_INVALID_WRITER_KEY: SharedResultCode.RESULT_CODE_ROLE_INVALID_WRITER_KEY,
    ROLE_INSUFFICIENT_FEE_BALANCE: SharedResultCode.RESULT_CODE_ROLE_INSUFFICIENT_FEE_BALANCE,
    MSB_BOOTSTRAP_MISMATCH: SharedResultCode.RESULT_CODE_MSB_BOOTSTRAP_MISMATCH,
    EXTERNAL_BOOTSTRAP_NOT_DEPLOYED: SharedResultCode.RESULT_CODE_EXTERNAL_BOOTSTRAP_NOT_DEPLOYED,
    EXTERNAL_BOOTSTRAP_TX_MISSING: SharedResultCode.RESULT_CODE_EXTERNAL_BOOTSTRAP_TX_MISSING,
    EXTERNAL_BOOTSTRAP_MISMATCH: SharedResultCode.RESULT_CODE_EXTERNAL_BOOTSTRAP_MISMATCH,
    BOOTSTRAP_ALREADY_EXISTS: SharedResultCode.RESULT_CODE_BOOTSTRAP_ALREADY_EXISTS,
    TRANSFER_RECIPIENT_ADDRESS_INVALID: SharedResultCode.RESULT_CODE_TRANSFER_RECIPIENT_ADDRESS_INVALID,
    TRANSFER_RECIPIENT_PUBLIC_KEY_INVALID: SharedResultCode.RESULT_CODE_TRANSFER_RECIPIENT_PUBLIC_KEY_INVALID,
    TRANSFER_AMOUNT_TOO_LARGE: SharedResultCode.RESULT_CODE_TRANSFER_AMOUNT_TOO_LARGE,
    TRANSFER_SENDER_NOT_FOUND: SharedResultCode.RESULT_CODE_TRANSFER_SENDER_NOT_FOUND,
    TRANSFER_INSUFFICIENT_BALANCE: SharedResultCode.RESULT_CODE_TRANSFER_INSUFFICIENT_BALANCE,
    TRANSFER_RECIPIENT_BALANCE_OVERFLOW: SharedResultCode.RESULT_CODE_TRANSFER_RECIPIENT_BALANCE_OVERFLOW,
    TX_HASH_INVALID_FORMAT: SharedResultCode.RESULT_CODE_TX_HASH_INVALID_FORMAT,
    INTERNAL_ENQUEUE_VALIDATION_FAILED: SharedResultCode.RESULT_CODE_INTERNAL_ENQUEUE_VALIDATION_FAILED,
    TX_COMMITTED_RECEIPT_MISSING: SharedResultCode.RESULT_CODE_TX_COMMITTED_RECEIPT_MISSING,
    VALIDATOR_RESPONSE_TX_TYPE_INVALID: SharedResultCode.RESULT_CODE_VALIDATOR_RESPONSE_TX_TYPE_INVALID,
    VALIDATOR_RESPONSE_TX_TYPE_UNKNOWN: SharedResultCode.RESULT_CODE_VALIDATOR_RESPONSE_TX_TYPE_UNKNOWN,
    VALIDATOR_RESPONSE_TX_TYPE_UNSUPPORTED: SharedResultCode.RESULT_CODE_VALIDATOR_RESPONSE_TX_TYPE_UNSUPPORTED,
    VALIDATOR_RESPONSE_SCHEMA_INVALID: SharedResultCode.RESULT_CODE_VALIDATOR_RESPONSE_SCHEMA_INVALID,
    PENDING_REQUEST_MISSING_TX_DATA: SharedResultCode.RESULT_CODE_PENDING_REQUEST_MISSING_TX_DATA,
    PROOF_PAYLOAD_MISMATCH: SharedResultCode.RESULT_CODE_PROOF_PAYLOAD_MISMATCH,
    VALIDATOR_WRITER_KEY_NOT_REGISTERED: SharedResultCode.RESULT_CODE_VALIDATOR_WRITER_KEY_NOT_REGISTERED,
    VALIDATOR_ADDRESS_MISMATCH: SharedResultCode.RESULT_CODE_VALIDATOR_ADDRESS_MISMATCH,
    VALIDATOR_NODE_ENTRY_NOT_FOUND: SharedResultCode.RESULT_CODE_VALIDATOR_NODE_ENTRY_NOT_FOUND,
    VALIDATOR_NODE_NOT_WRITER: SharedResultCode.RESULT_CODE_VALIDATOR_NODE_NOT_WRITER,
    VALIDATOR_WRITER_KEY_MISMATCH: SharedResultCode.RESULT_CODE_VALIDATOR_WRITER_KEY_MISMATCH,
    VALIDATOR_TX_OBJECT_INVALID: SharedResultCode.RESULT_CODE_VALIDATOR_TX_OBJECT_INVALID,
    VALIDATOR_VA_MISSING: SharedResultCode.RESULT_CODE_VALIDATOR_VA_MISSING,
    TX_INVALID_PAYLOAD: SharedResultCode.RESULT_CODE_TX_INVALID_PAYLOAD
});

// TODO: Refactor network code to use NetworkResultCode instead of "old" ResultCode
//       Then, remove the line below 
export const ResultCode = NetworkResultCode; // TO BE DEPRECATED

// Role managment constants
export const EventType = Object.freeze({
    WRITER_EVENT: 'writer-event',
    IS_INDEXER: 'is-indexer',
    IS_NON_INDEXER: 'is-non-indexer',
    WRITABLE: 'writable',
    UNWRITABLE: 'unwritable',
    WARNING: 'warning',
    VALIDATOR_HEALTH_CHECK: 'validator-health-check',
});

// Role managment constants
export const CustomEventType = Object.freeze({
    IS_INDEXER: 'msb:is-indexer',
    UNWRITABLE: 'msb:unwritable',
    IS_NON_INDEXER: 'msb:is-non-indexer',
    EPOCH_PROPOSAL_SUBMITTED: 'msb:epoch_proposal_submitted',
    EPOCH_PROPOSAL_RECEIVED: 'msb:epoch_proposal_received',
    EPOCH_PROPOSAL_VALIDATION_SUCCESS: 'msb:epoch_proposal_validation_success',
    EPOCH_PROPOSAL_VALIDATION_FAILURE: 'msb:epoch_proposal_validation_failure',
    EPOCH_PROPOSAL_APPROVAL_RECEIVED: 'msb:epoch_proposal_approval_received',
    EPOCH_PROPOSAL_APPROVAL_SUCCESS: 'msb:epoch_proposal_approval_success',
    EPOCH_PROPOSAL_APPROVAL_FAILURE: 'msb:epoch_proposal_approval_failure',
    EPOCH_CREATED: 'msb:epoch_created'
});

// Token
export const TOKEN_DECIMALS = 18n
export const ADMIN_INITIAL_BALANCE = b4a.from([0, 0, 0, 0, 0, 0, 0, 54, 53, 201, 173, 197, 222, 160, 0, 0]) // 1000 in a 18 decimals token
export const ADMIN_INITIAL_STAKED_BALANCE = b4a.from([0, 0, 0, 0, 0, 0, 0, 0,4, 41, 208, 105, 24, 158, 0, 0]) // 0.3 in a 18 decimals token

export const WHITELIST_FILEPATH = './whitelist/addresses.csv';
export const BALANCE_MIGRATION_FILEPATH = './migration/initial_balances.csv';
export const BALANCE_MIGRATED_DIR = './migration/migrated/';
export const WHITELIST_MIGRATION_DIR = './whitelist/migrated/';
export const TRAC_NAMESPACE = 'TracNetwork';
export const WHITELIST_SLEEP_INTERVAL = 1_000;
export const BALANCE_MIGRATION_SLEEP_INTERVAL = 500;

// State
export const ACK_INTERVAL = 1_000;
export const AUTOBASE_VALUE_ENCODING = 'binary';
export const HYPERBEE_KEY_ENCODING = 'ascii';
export const HYPERBEE_VALUE_ENCODING = 'binary';
// StateValidationSchema.js

//ATTENTION - THIS IS USED IN THE APPLY FUNCTION!
// Apply schema validation
export const PUBLIC_KEY_LENGTH = 32
export const WRITER_BYTE_LENGTH = 32;
export const BOOTSTRAP_BYTE_LENGTH = 32;
export const CHANNEL_BYTE_LENGTH = 32;
export const NONCE_BYTE_LENGTH = 32;
export const HASH_BYTE_LENGTH = 32;
export const BALANCE_BYTE_LENGTH = 16;
export const SIGNATURE_BYTE_LENGTH = 64;
export const PEER_PUBLIC_KEY_HEX_LENGTH = 64;
export const AMOUNT_BYTE_LENGTH = 16;
export const UINT16_MAX = 0xFFFF;
export const UINT32_MAX = 0xFFFFFFFF;

// consensus
export const PROTOCOL_VERSION_BYTE_LENGTH = 1; // 1 BYTE 0-255
export const NETWORK_ID_BYTE_LENGTH = 2; // 2 BYTES - UINT16
export const EPOCH_BYTE_LENGTH = 8; // 8 BYTES - UINT64
export const VDF_DIFFICULTY_SIZE = 4; // 4 BYTES - UINT32
export const VDF_DISCRIMINANT_SIZE = 2; // 2 BYTES - UINT16
export const MAX_VDF_DIFFICULTY = UINT32_MAX;
export const CONSENSUS_CONFIG_SCHEMA_VERSION_BYTE_LENGTH = 1;
export const CONSENSUS_CONFIG_DATA_MAX_SIZE = 3072; // 3 KiB
export const VDF_PROOF_BYTE_LENGTHS = Object.freeze({
    1024: 260,
    2048: 516,
    4096: 1028
});

export const LICENSE_BYTE_LENGTH = 4;

// index.js
export const BOOTSTRAP_HEXSTRING_LENGTH = 64;

// Pool constants
export const BATCH_SIZE = 10;

// Operation handler constants
export const MAX_PARTIAL_TX_PAYLOAD_BYTE_SIZE = 3072;
export const V1_PROTOCOL_PAYLOAD_MAX_SIZE = 4096;
export const CONSENSUS_MESSAGE_MAX_BYTE_SIZE = 4096;

// Transaction Commit Service
export const TRANSACTION_COMMIT_SERVICE_BUFFER_SIZE = 1500;

// Network message constants
export const NETWORK_MESSAGE_TYPES = Object.freeze({
    GET: {
        VALIDATOR: 'get_validator_pop',
        ADMIN: 'get_admin_pop',
        NODE: 'get_node_pop'
    },

    RESPONSE: {
        VALIDATOR: 'validatorResponse',
        ADMIN: 'adminResponse',
        NODE: 'nodeResponse'
    },
});

export const NETWORK_CAPABILITIES = Object.freeze(["protocols:v1:legacy"]);

// Network tryConnect status constants
export const CONNECTION_STATUS = Object.freeze({
    CONNECTED: 0,
    PENDING: 1,
    IGNORED: 2
});
