export const SharedValidatorErrorCode = Object.freeze({
    // Generic / schema-level
    PAYLOAD_TYPE_MISSING: 'PAYLOAD_TYPE_MISSING',
    PAYLOAD_SCHEMA_INVALID: 'PAYLOAD_SCHEMA_INVALID',
    OPERATION_TYPE_UNKNOWN: 'OPERATION_TYPE_UNKNOWN',

    // Requester identity
    REQUESTER_ADDRESS_INVALID: 'REQUESTER_ADDRESS_INVALID',
    REQUESTER_PUBLIC_KEY_INVALID: 'REQUESTER_PUBLIC_KEY_INVALID',

    // Transaction hashing/signing
    TX_HASH_MISMATCH: 'TX_HASH_MISMATCH',
    TX_SIGNATURE_INVALID: 'TX_SIGNATURE_INVALID',

    // TX lifecycle / replay
    TX_EXPIRED: 'TX_EXPIRED',
    TX_ALREADY_EXISTS: 'TX_ALREADY_EXISTS',
    OPERATION_ALREADY_COMPLETED: 'OPERATION_ALREADY_COMPLETED',

    // Fee & requester state
    REQUESTER_NOT_FOUND: 'REQUESTER_NOT_FOUND',
    INSUFFICIENT_FEE_BALANCE: 'INSUFFICIENT_FEE_BALANCE',

    // Subnet bootstrap / self-validation guard
    EXTERNAL_BOOTSTRAP_EQUALS_MSB_BOOTSTRAP: 'EXTERNAL_BOOTSTRAP_EQUALS_MSB_BOOTSTRAP',
    SELF_VALIDATION_FORBIDDEN: 'SELF_VALIDATION_FORBIDDEN',

    // Role access
    ROLE_NODE_ENTRY_NOT_FOUND: 'ROLE_NODE_ENTRY_NOT_FOUND',
    ROLE_NODE_ALREADY_WRITER: 'ROLE_NODE_ALREADY_WRITER',
    ROLE_NODE_NOT_WHITELISTED: 'ROLE_NODE_NOT_WHITELISTED',
    ROLE_NODE_NOT_WRITER: 'ROLE_NODE_NOT_WRITER',
    ROLE_NODE_IS_INDEXER: 'ROLE_NODE_IS_INDEXER',
    ROLE_ADMIN_ENTRY_MISSING: 'ROLE_ADMIN_ENTRY_MISSING',
    ROLE_INVALID_RECOVERY_CASE: 'ROLE_INVALID_RECOVERY_CASE',
    ROLE_UNKNOWN_OPERATION: 'ROLE_UNKNOWN_OPERATION',
    ROLE_INVALID_WRITER_KEY: 'ROLE_INVALID_WRITER_KEY',
    ROLE_INSUFFICIENT_FEE_BALANCE: 'ROLE_INSUFFICIENT_FEE_BALANCE',

    // Transaction operation
    MSB_BOOTSTRAP_MISMATCH: 'MSB_BOOTSTRAP_MISMATCH',
    EXTERNAL_BOOTSTRAP_NOT_DEPLOYED: 'EXTERNAL_BOOTSTRAP_NOT_DEPLOYED',
    EXTERNAL_BOOTSTRAP_TX_MISSING: 'EXTERNAL_BOOTSTRAP_TX_MISSING',
    EXTERNAL_BOOTSTRAP_MISMATCH: 'EXTERNAL_BOOTSTRAP_MISMATCH',

    // Bootstrap deployment
    BOOTSTRAP_ALREADY_EXISTS: 'BOOTSTRAP_ALREADY_EXISTS',

    // Transfers
    TRANSFER_RECIPIENT_ADDRESS_INVALID: 'TRANSFER_RECIPIENT_ADDRESS_INVALID',
    TRANSFER_RECIPIENT_PUBLIC_KEY_INVALID: 'TRANSFER_RECIPIENT_PUBLIC_KEY_INVALID',
    TRANSFER_AMOUNT_TOO_LARGE: 'TRANSFER_AMOUNT_TOO_LARGE',
    TRANSFER_SENDER_NOT_FOUND: 'TRANSFER_SENDER_NOT_FOUND',
    TRANSFER_INSUFFICIENT_BALANCE: 'TRANSFER_INSUFFICIENT_BALANCE',
    TRANSFER_RECIPIENT_BALANCE_OVERFLOW: 'TRANSFER_RECIPIENT_BALANCE_OVERFLOW',

    // Implementation / internal
    VALIDATOR_METHOD_NOT_IMPLEMENTED: 'VALIDATOR_METHOD_NOT_IMPLEMENTED',
});

export class SharedValidatorError extends Error {
    /**
     * @param {string} code Error code for translation into protocol errors.
     * @param {string} message Human-readable message.
     */
    constructor(code, message) {
        super(message);
        this.name = this.constructor.name;
        this.code = code;
    }
}
