import { StateMachine } from "../../../utils/StateMachine.js";

export const EPOCH_STATES = Object.freeze({
    LOAD_EPOCH_CONTEXT: "LOAD_EPOCH_CONTEXT",
    INITIALIZE_VDF: "INITIALIZE_VDF",
    BUILD_AND_SIGN_PROOF_PROPOSAL: "BUILD_AND_SIGN_PROOF_PROPOSAL",
    SEND_PROPOSAL_TO_INDEXERS: "SEND_PROPOSAL_TO_INDEXERS",
    COLLECT_APPROVALS: "COLLECT_APPROVALS",
    QUORUM_DECISION: "QUORUM_DECISION",
    BUILD_SET_EPOCH: "BUILD_SET_EPOCH",
    REFRESH_SIGNED_STATE_BEFORE_APPEND: "REFRESH_SIGNED_STATE_BEFORE_APPEND",
    APPEND_SET_EPOCH: "APPEND_SET_EPOCH",
    SEND_APPEND_SIGNAL: "SEND_APPEND_SIGNAL", // Terminal on purpose: no state is preserved across cycles, so there is nothing to hand off to BACKOFF.
    REFRESH_SIGNED_STATE: "REFRESH_SIGNED_STATE",
    BACKOFF: "BACKOFF",
    RELOAD_SIGNED_CONTEXT: "RELOAD_SIGNED_CONTEXT",
});

export const EPOCH_EVENTS = Object.freeze({
    START: "START",
    STOP: "STOP",
    LOCAL_PROOF_READY: "LOCAL_PROOF_READY",
    PROPOSAL_BUILT: "PROPOSAL_BUILT",
    EXTERNAL_APPROVALS_REQUIRED: "EXTERNAL_APPROVALS_REQUIRED",
    EXTERNAL_APPROVALS_NOT_REQUIRED: "EXTERNAL_APPROVALS_NOT_REQUIRED",
    PROPOSAL_BROADCAST: "PROPOSAL_BROADCAST",
    APPROVAL_COLLECTED: "APPROVAL_COLLECTED",
    QUORUM_REACHED: "QUORUM_REACHED",
    PEER_EPOCH_MISMATCH: "PEER_EPOCH_MISMATCH",
    APPROVAL_COLLECTION_FAILED: "APPROVAL_COLLECTION_FAILED",
    SET_EPOCH_BUILT: "SET_EPOCH_BUILT",
    SIGNED_STATE_REFRESHED: "SIGNED_STATE_REFRESHED",
    TARGET_EPOCH_ABSENT: "TARGET_EPOCH_ABSENT",
    TARGET_EPOCH_ALREADY_SIGNED: "TARGET_EPOCH_ALREADY_SIGNED",
    APPEND_ACCEPTED: "APPEND_ACCEPTED",
    APPEND_FAILED: "APPEND_FAILED",
    APPEND_SIGNAL_SENT: "APPEND_SIGNAL_SENT",
    BACKOFF_ELAPSED: "BACKOFF_ELAPSED",
    EPOCH_UNCHANGED_WITHOUT_LOCAL_PROOF: "EPOCH_UNCHANGED_WITHOUT_LOCAL_PROOF",
    EPOCH_UNCHANGED_WITH_LOCAL_PROOF: "EPOCH_UNCHANGED_WITH_LOCAL_PROOF",
    NEW_EPOCH_DISCOVERED: "NEW_EPOCH_DISCOVERED",
    SIGNED_CONTEXT_CHANGED: "SIGNED_CONTEXT_CHANGED",
    CONTEXT_RELOADED: "CONTEXT_RELOADED",
    SOLVER_FAILURE: "SOLVER FAILURE",
});

const TRANSITIONS = {
    [EPOCH_STATES.LOAD_EPOCH_CONTEXT]: Object.freeze({
        [EPOCH_EVENTS.START]: EPOCH_STATES.INITIALIZE_VDF,
    }),
    [EPOCH_STATES.INITIALIZE_VDF]: Object.freeze({
        [EPOCH_EVENTS.LOCAL_PROOF_READY]: EPOCH_STATES.BUILD_AND_SIGN_PROOF_PROPOSAL,
        [EPOCH_EVENTS.SOLVER_FAILURE]: EPOCH_STATES.INITIALIZE_VDF,
    }),
    [EPOCH_STATES.BUILD_AND_SIGN_PROOF_PROPOSAL]: Object.freeze({
        [EPOCH_EVENTS.PROPOSAL_BUILT]: EPOCH_STATES.QUORUM_DECISION,
    }),
    [EPOCH_STATES.QUORUM_DECISION]: Object.freeze({
        [EPOCH_EVENTS.EXTERNAL_APPROVALS_NOT_REQUIRED]: EPOCH_STATES.BUILD_SET_EPOCH,
        [EPOCH_EVENTS.EXTERNAL_APPROVALS_REQUIRED]: EPOCH_STATES.SEND_PROPOSAL_TO_INDEXERS,
        [EPOCH_EVENTS.TARGET_EPOCH_ALREADY_SIGNED]: EPOCH_STATES.RELOAD_SIGNED_CONTEXT,
    }),
    [EPOCH_STATES.SEND_PROPOSAL_TO_INDEXERS]: Object.freeze({
        [EPOCH_EVENTS.PROPOSAL_BROADCAST]: EPOCH_STATES.COLLECT_APPROVALS,
    }),
    [EPOCH_STATES.COLLECT_APPROVALS]: Object.freeze({
        [EPOCH_EVENTS.APPROVAL_COLLECTED]: EPOCH_STATES.COLLECT_APPROVALS,
        [EPOCH_EVENTS.QUORUM_REACHED]: EPOCH_STATES.BUILD_SET_EPOCH,
        [EPOCH_EVENTS.PEER_EPOCH_MISMATCH]: EPOCH_STATES.REFRESH_SIGNED_STATE,
        [EPOCH_EVENTS.APPROVAL_COLLECTION_FAILED]: EPOCH_STATES.BACKOFF,
    }),
    [EPOCH_STATES.BUILD_SET_EPOCH]: Object.freeze({
        [EPOCH_EVENTS.SET_EPOCH_BUILT]: EPOCH_STATES.REFRESH_SIGNED_STATE_BEFORE_APPEND,
    }),
    [EPOCH_STATES.REFRESH_SIGNED_STATE_BEFORE_APPEND]: Object.freeze({
        [EPOCH_EVENTS.TARGET_EPOCH_ABSENT]: EPOCH_STATES.APPEND_SET_EPOCH,
        [EPOCH_EVENTS.TARGET_EPOCH_ALREADY_SIGNED]: EPOCH_STATES.RELOAD_SIGNED_CONTEXT,
    }),
    [EPOCH_STATES.APPEND_SET_EPOCH]: Object.freeze({
        [EPOCH_EVENTS.APPEND_ACCEPTED]: EPOCH_STATES.SEND_APPEND_SIGNAL,
        [EPOCH_EVENTS.APPEND_FAILED]: EPOCH_STATES.BACKOFF,
        [EPOCH_EVENTS.TARGET_EPOCH_ALREADY_SIGNED]: EPOCH_STATES.RELOAD_SIGNED_CONTEXT,
    }),
    [EPOCH_STATES.REFRESH_SIGNED_STATE]: Object.freeze({
        [EPOCH_EVENTS.EPOCH_UNCHANGED_WITHOUT_LOCAL_PROOF]: EPOCH_STATES.INITIALIZE_VDF,
        [EPOCH_EVENTS.EPOCH_UNCHANGED_WITH_LOCAL_PROOF]: EPOCH_STATES.BUILD_AND_SIGN_PROOF_PROPOSAL,
        [EPOCH_EVENTS.NEW_EPOCH_DISCOVERED]: EPOCH_STATES.RELOAD_SIGNED_CONTEXT,
    }),
    [EPOCH_STATES.BACKOFF]: Object.freeze({
        [EPOCH_EVENTS.BACKOFF_ELAPSED]: EPOCH_STATES.REFRESH_SIGNED_STATE,
    }),
    [EPOCH_STATES.RELOAD_SIGNED_CONTEXT]: Object.freeze({
        // Hard reset is mandatory here: the VDF challenge is derived from currentEpoch/currentEpochHash,
        // which just changed, so the old proof is not reusable.
        [EPOCH_EVENTS.CONTEXT_RELOADED]: EPOCH_STATES.INITIALIZE_VDF,
    }),
};

export class EpochStateMachine extends StateMachine {
    constructor(handlers = {}) {
        super(TRANSITIONS, EPOCH_STATES.LOAD_EPOCH_CONTEXT, EPOCH_STATES.LOAD_EPOCH_CONTEXT, handlers);
    }
}
