import b4a from 'b4a';
import _ from 'lodash';
import stateGenerated from './state.generated.cjs';

const {EscrowEntry} = stateGenerated.state;
const TO_OBJECT_OPTIONS = Object.freeze({
    enums: Number,
    bytes: Buffer,
    defaults: false,
});

// These wrappers validate protobuf structure; settlement rules remain in the state helper.
export const encodeEscrowEntry = entry => {
    if (!_.isPlainObject(entry)) throw new Error('Escrow entry must be an object.');
    const error = EscrowEntry.verify(entry);
    if (error) throw new Error(error);
    return b4a.from(EscrowEntry.encode(entry).finish());
};

export const decodeEscrowEntry = encoded => {
    if (!b4a.isBuffer(encoded) || encoded.length === 0) {
        throw new Error('Encoded escrow entry must be a non-empty buffer.');
    }
    const decoded = EscrowEntry.toObject(EscrowEntry.decode(encoded), TO_OBJECT_OPTIONS);
    // Generated byte fields may alias the input; return independent buffers.
    for (const [field, value] of Object.entries(decoded)) {
        if (b4a.isBuffer(value)) decoded[field] = b4a.from(value);
    }
    return decoded;
};

export const safeEncodeEscrowEntry = entry => {
    try {
        return encodeEscrowEntry(entry);
    } catch {
        return b4a.alloc(0);
    }
};

export const safeDecodeEscrowEntry = encoded => {
    try {
        return decodeEscrowEntry(encoded);
    } catch {
        return null;
    }
};
