// This runner is auto-generated by Brittle

import { default as test } from 'brittle';

async function runTests() {
	test.pause();
	await import('./network/networkModule.test.js')
	await import('./state/stateModule.test.js');
    await import('./messages/applyStateMessageBuilderRegTests.test.js');
	await import('./utils/utils.test.js');
	// await import('./messages/stateMessageOperations.test.js'); // Broken test - needs fixing
	test.resume();
}

await runTests();
