syntax = "proto3";

package apply.operations;

import "applyOperations/enums/operation_type.proto";
import "applyOperations/messages/core_admin_operation.proto";
import "applyOperations/messages/admin_control_operation.proto";
import "applyOperations/messages/balance_initialization_operation.proto";
import "applyOperations/messages/transfer_operation.proto";
import "applyOperations/messages/role_access_operation.proto";
import "applyOperations/messages/bootstrap_deployment_operation.proto";
import "applyOperations/messages/tx_operation.proto";
import "applyOperations/messages/set_epoch_operation.proto";
import "applyOperations/messages/set_genesis_epoch_operation.proto";
import "applyOperations/messages/set_consensus_config_operation.proto";

// Main structure for the operations where messages are
message Operation {
    OperationType type = 1;
    bytes address      = 2; // address of the invoker

    oneof value {
        CoreAdminOperation                cao  = 3;
        AdminControlOperation             aco  = 4;
        BalanceInitializationOperation    bio  = 5;
        TransferOperation                 tro  = 6;
        RoleAccessOperation               rao  = 7;
        BootstrapDeploymentOperation      bdo  = 8;
        TxOperation                       txo  = 9;
        SetEpochOperation                 seo  = 10;
        SetGenesisEpochOperation          sgo  = 11;
        SetConsensusConfigOperation       cco  = 12;
    }
}
